//
// Created by audri on 24/11/2023.
//

#ifndef OPTIMISATION_D_UNE_LIGNE_D_ASSEMBLAGE_TD12_GRP9_MENUDELANCEMENT_H
#define OPTIMISATION_D_UNE_LIGNE_D_ASSEMBLAGE_TD12_GRP9_MENUDELANCEMENT_H

#include "stdio.h"
int menu_de_lancement();
#endif //OPTIMISATION_D_UNE_LIGNE_D_ASSEMBLAGE_TD12_GRP9_MENUDELANCEMENT_H
